# Site settings
title: "James Magnarelli"
email: "jmagnare@gmail.com"
description: "I'm a Software Developer in the Boston area. 
I enjoy building things through rapid experimentation with customers."
baseurl: ""
url: "http://www.magnarelli.org"

# Build settings
markdown: kramdown

# Don't put these in _site
exclude: [config.rb, sass]
